- hosts: compute[0]
  tasks:
  - name: create io500_install.sh file
    template:
      src: _io500_install.sh.j2
      dest: /home/opc/io500_install.sh
  - name: copy io500.sh file
    template:
      src: io500.sh
      dest: /home/opc/io500.sh
    run_once: true
  - name: copy io500 config*ini file
    template:
      src: config-oci.ini
      dest: /home/opc/config-oci.ini
    run_once: true
  - name: Install io500 benchmark on first compute node only
    command: bash -c "chmod +x /home/opc/*.sh ; sudo /home/opc/io500_install.sh "
    run_once: true
