# tasks/hosts.yml

- hosts: all 
  become: true
  gather_facts: true
  tasks: 
  - name: stop firewalld
    service: 
      name: firewalld
      state: stopped
      enabled: no
    async: 30
    poll: 0
  - name: Update /etc/oci-hostname.conf
    lineinfile: 
      path: /etc/oci-hostname.conf
      regexp: '^PRESERVE_HOSTINFO=0'
      line: 'PRESERVE_HOSTINFO=2'
  - name: create temporary /etc/hosts file
    blockinfile:
      dest: /tmp/hosts
      content: "{{ lookup('template', '_hosts.j2') }}"
      state: present
      create: yes
    delegate_to: 127.0.0.1
    run_once: true
  - name: create /etc/hosts on all servers
    become: true
    blockinfile: 
      dest: /etc/hosts
      content: "{{ lookup('file', '/tmp/hosts') }}"
      state: present
    async: 30 
    poll: 0 
  - name: update global known_hosts file
    become: true
    template:
      force: true
      backup: true
      dest: /etc/ssh/ssh_known_hosts
      src: _known_hosts.j2
    tags: known_hosts
    delegate_to: 127.0.0.1
    run_once: true
  - name: place the known SSH hosts on every node
    become: true
    copy:
      src: /etc/ssh/ssh_known_hosts
      dest: /etc/ssh/ssh_known_hosts
      owner: root
      group: root
      mode: 644
  - name: place the private SSH key on every node
    become: true
    copy: 
      src: /home/opc/.ssh/id_rsa
      dest: /home/opc/.ssh/id_rsa
      owner: opc
      group: opc
      mode: 0600
  - name: Create /etc/opt/oci-hpc/ directory if it does not exist
    file:
      path: /etc/opt/oci-hpc
      state: directory
      mode: '0755'
  - name: create rdma hostfile
    template: 
      src: _hostfile_rdma.j2
      dest: /etc/opt/oci-hpc/hostfile.rdma
    tags: hostfile
    delegate_to: 127.0.0.1
    run_once: true
  - name: create tcp hostfile
    template: 
      src: _hostfile_tcp.j2
      dest: /etc/opt/oci-hpc/hostfile.tcp
    tags: hostfile
    delegate_to: 127.0.0.1
    run_once: true
  - name: place the RDMA hostfile on every node
    become: true
    copy:
      src: /etc/opt/oci-hpc/hostfile.rdma
      dest: /etc/opt/oci-hpc/hostfile.rdma
      owner: root
      group: root
      mode: 644
  - name: place the TCP hostfile on every node
    become: true
    copy:
      src: /etc/opt/oci-hpc/hostfile.tcp
      dest: /etc/opt/oci-hpc/hostfile.tcp
      owner: root
      group: root
      mode: 644

- hosts: compute
  gather_facts: True
  become: true
  handlers:
  - name: restart_interface
    command: bash -c "ifdown enp94s0f0 && ifup enp94s0f0"
    when: rdma_interface.changed
  tasks: 
  - name: Create a symbolic link
    file:
      src: /etc/opt/oci-hpc/hostfile.rdma
      dest: /etc/opt/oci-hpc/hostfile
      owner: root
      group: root
      state: link
      mode: 0644
  - name: create interface files
    register: rdma_interface
    notify: restart_interface
    template: 
      src: _ifcfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-enp94s0f0
  - name: Create a new primary partition
    parted:
      device: /dev/nvme0n1
      number: 1
      state: present
      label: gpt
  - name: create a filesystem
    filesystem: 
      dev: /dev/nvme0n1p1
      fstype: xfs
  - name: Mount local volume
    mount:
      path: /mnt/localdisk/
      src: /dev/nvme0n1p1
      fstype: xfs
      opts: defaults,noatime,inode64
      state: mounted

- import_playbook: beeond.yml
  when:
    - filesystem == "beegfs"
